export const POST_OFFICES_REQUEST_PENDING = 'POST_OFFICES_REQUEST_PENDING';
export const POST_OFFICES_REQUEST_FULFILLED = 'POST_OFFICES_REQUEST_FULFILLED';

export const LOAD_POST_OFFICES = 'LOAD_POST_OFFICES';