export const SOLD_PRODUCTS_REQUEST_PENDING = 'SOLD_PRODUCTS_REQUEST_PENDING';
export const SOLD_PRODUCTS_REQUEST_FULFILLED = 'SOLD_PRODUCTS_REQUEST_FULFILLED';

export const LOAD_SOLD_PRODUCTS = 'LOAD_SOLD_PRODUCTS';